@startuml
title Diagrama de Casos de Uso - Sistema de Aluguel de Carros

actor "Usuário" as Usuario
actor "Cliente" as Cliente
actor "Agente" as Agente

Usuario <|-- Cliente
Usuario <|-- Agente

' Casos de uso de autenticação
usecase "Realizar Cadastro/Registro" as UC_Cadastrar
usecase "Realizar Login" as UC_Login

' Casos de uso do Cliente
usecase "Criar Pedido" as UC_CriarPedido
usecase "Consultar Pedido" as UC_ConsultarPedido
usecase "Cancelar Pedido" as UC_CancelarPedido
usecase "Visualizar Proprietário do Automóvel" as UC_VisualizarProprietario
usecase "Gerenciar Dados Pessoais" as UC_GerenciarDadosPessoais

' Casos de uso do Agente
usecase "Avaliar Pedidos" as UC_AvaliarPedido
usecase "Gerenciar Automóveis" as UC_GerenciarAutomoveis
usecase "Vizualizar contrato" as UC_VizualizarContrato
usecase "Excluir contrato" as UC_ExcluirContrato
usecase "Alterar contrato" as UC_AlterarContrato

' Casos de uso do Agente e cliente
usecase "Modificar Pedido" as UC_ModificarPedido
usecase "Registrar Contrato" as UC_RegistrarContrato

' Relacionamentos
Usuario -- UC_Cadastrar
Usuario -- UC_Login
Usuario -- UC_ModificarPedido

Cliente -- UC_CriarPedido
Cliente -- UC_ConsultarPedido
Cliente -- UC_CancelarPedido
Cliente -- UC_VisualizarProprietario
Cliente -- UC_GerenciarDadosPessoais

Agente -- UC_AvaliarPedido
Agente -- UC_RegistrarContrato
Agente -- UC_GerenciarAutomoveis
Agente -- UC_VizualizarContrato
Agente -- UC_ExcluirContrato
Agente -- UC_AlterarContrato

UC_RegistrarContrato --> Cliente
@enduml
